export const USER_LOGIN_FAILED_ERROR = 'USER_LOGIN_FAILED_ERROR ';
export const USER_LOGOUT_FAILED_ERROR = 'USER_LOGOUT_FAILED_ERROR';
export const TOKEN_REISSUE_ERROR = 'TOKEN_REISSUE_ERROR';
export const USER_SOCIAL_LOGIN_FAILED_ERROR = 'USER_SOCIAL_LOGIN_FAILED_ERROR';
